#ifndef __CSI_CONFIG_H__
#define __CSI_CONFIG_H__
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_RV32EMC 1
#define CONFIG_CHIP_WUJIAN100_OPEN 1
#define CONFIG_BOARD_WUJIAN100_OPEN_EVB 1
#define CONFIG_BOARD_NAME_STR "wujian100_open_evb"
#define CONFIG_KERNEL_RHINO 1
#define CONFIG_ARCH_INTERRUPTSTACK 4096
#define CONFIG_NEWLIB_WRAP 1
#define CONFIG_USER_DEFINED_LD_DIR_STR ""
#endif
